name: Publish on pull request merged

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use Node LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: "Setup NPM" # Add our registry to npm config
        run: | # Custom action
          npm set @ORGANIZATION:registry=https://npm.pkg.github.com/ORGANIZATION
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Version and publish" # publish package
        env:
          GH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = next ]; then
            npx lerna version --conventional-commits --conventional-graduate --yes
            npx lerna publish from-git --dist-tag next --yes
          elif [ ${{ github.base_ref }} = beta ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
            npx lerna publish from-git --pre-dist-tag beta  --yes
          elif [ ${{ github.base_ref }} = alpha ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid alpha --yes
            npx lerna publish from-git --pre-dist-tag alpha  --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
            npx lerna publish from-git --yes
          fi
