name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Setup npm" # Add our registry to npm config
        run: | # Custom action
          npm set @smerth:registry=https://npm.pkg.github.com/smerth
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Version and publish" # publish package
        env:
          GH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = development ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
          fi

          npx lerna publish from-git --yes

      # - name: Edit .npmrc
      #   run: |
      #     echo "registry=https://registry.npmjs.org" > .npmrc
      #     echo "@smerth=https://npm.pkg.github.com/smerth" >> .npmrc
      #     echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # - name: Release & Publish
      #   uses: cycjimmy/semantic-release-action@v2
      #   id: semantic

      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
